name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
          cd polls/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run Django management commands
      run: |
          cd polls/ &&
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          python manage.py loaddata fixtures/initial_data.json &&
          uwsgi --ini uwsgi.ini

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Ensure this is set

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: 841162710116.dkr.ecr.us-east-2.amazonaws.com/sherpany-polls:${{ github.sha }} # Update this with your ECR repository URI

