name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: 841162710116.dkr.ecr.us-east-2.amazonaws.com/sherpany-polls:${{ github.sha }} # Update this with your ECR repository URI

