name: Setup PostgreSQL

on:
  workflow_dispatch: 

jobs:
  apply-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  

      - name: Configure kubectl for EKS
        run: |
            aws eks update-kubeconfig --region us-east-2 --name sherpany-polls
  
    
      - name: Install Chamber (Secrets Manager)
        run: |
            curl -Lo chamber https://github.com/segmentio/chamber/releases/download/v2.10.5/chamber-v2.10.5-linux-amd64
            chmod +x chamber
            sudo mv chamber /usr/local/bin/

      - name: Pull secrets with Chamber and set environment variables
        env:
            CHAMBER_SERVICE_NAME: "sherpany-polls"  # Replace with your service name in Parameter Store
        run: |
            export $(chamber env $CHAMBER_SERVICE_NAME)
      
      - name: Substitute secrets in manifest
        run: |
            envsubst < infra/postgres/secrets.yaml.tpl > secrets.yaml

      - name: Apply secrets Manifest to Kubernetes
        run: |
         kubectl apply -f secrets.yaml

      - name: Apply postgres Manifest to Kubernetes
        run: |
         kubectl apply -f infra/postgres/main.yaml
         kubectl rollout restart deployment postgres