name: Setup PostgreSQL

on:
  workflow_dispatch: 

jobs:
  apply-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assume IAM role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GitHubActions
      
      - name: Configure kubectl for EKS
        run: |
            aws eks update-kubeconfig --region ${{ vars.AWS_DEFAULT_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}
    
      - name: Install Chamber (Secrets Manager)
        run: |
            curl -Lo chamber https://github.com/segmentio/chamber/releases/download/v2.10.5/chamber-v2.10.5-linux-amd64
            chmod +x chamber
            sudo mv chamber /usr/local/bin/

      - name: Pull secrets with Chamber and set environment variables
        env:
            CHAMBER_SERVICE_NAME: "${{ vars.EKS_CLUSTER_NAME }}" 
        run: |
            export $(chamber env $CHAMBER_SERVICE_NAME)
      
      - name: Substitute secrets in manifest
        run: |
            envsubst < infra/postgres/secrets.yaml.tpl > secrets.yaml

      - name: Apply secrets Manifest to Kubernetes
        run: |
         kubectl apply -f secrets.yaml

      - name: Apply postgres Manifest to Kubernetes
        run: |
         kubectl apply -f infra/postgres/main.yaml
         kubectl rollout restart deployment postgres